### ISSUE TITLE
Magento 2.4.6 compatibility

### ISSUE THREAD

**Issue by Fidelity88** [magento/meta-for-magento2#1]
When trying to install the official Meta for Magento2 extension from the Magento Repo, the installation fails because of requirements:

`meta/module-business-extension 1.0.0 requires magento/module-store >=101.1.4 <=101.1.5`

Magento 2.4.6 uses version 101.1.6 and thus Meta extension cannot be installed on the latest Magento version.

https://marketplace.magento.com/meta-meta-for-magento2.html

### Preconditions (*)
1. Magento 2.4.6
2. [meta/meta-for-magento2](https://marketplace.magento.com/meta-meta-for-magento2.html) 1.0.0

### Steps to reproduce (*)
1. composer require meta/meta-for-magento2 on Magento 2.4.6

### Expected result (*)
Usable Meta extension on the latest Magento2 version released on 14th of March 2023

### Actual result (*)

```
Your requirements could not be resolved to an installable set of packages

- meta/module-business-extension 1.0.0 requires magento/module-store >=101.1.4 <=101.1.5
```

**Comment by holzkern** [comment]
Basically same issue with Magento 2.4.5-p2:
meta/module-business-extension 1.0.0 requires magento/framework >=103.0.4 <=103.0.5-p1 -> found magento/framework[103.0.4, ..., 103.0.5-p1] but the package is fixed to 103.0.5-p2

**Comment by btantlinger** [comment]
Same issue.  Unable to use either old facebook-for-magento2  or meta-for-magento2 module due to this issue.

**Comment by gscogna** [comment]
I have a similar problem but my version is 2.4.1 I don't have the php requirements to install it do you know an alternative to this module.

**Comment by DannyDaemonic** [comment]
How is a major company like this so far behind?

**Comment by PhiIipp** [comment]
Yeh my integration is also down since two month. :(.
Think a community member did a unofficial fork on other repository and fixed it but don’t want to use unofficial sources .

**Comment by Fidelity88** [comment]
> Think a community member did a unofficial fork on other repository and fixed it but don’t want to use unofficial sources .

Can you send a link? Would love to check it out, if this bug persists any longer I have no choice but to use the unofficial source

**Comment by PhiIipp** [comment]
> > Think a community member did a unofficial fork on other repository and fixed it but don’t want to use unofficial sources .
> 
> Can you send a link? Would love to check it out, if this bug persists any longer I have no choice but to use the unofficial source

I mean the comment (was on my mobile and didnt see all comments ) from above https://github.com/magento/meta-for-magento2/issues/1#issuecomment-1532770288 , but saw this might be a old version which got fixed

**Comment by zlik** [comment]
Hi @Fidelity88, support for Magento v2.4.6 is coming up in a few weeks, please stay tuned for updates! Apologize for any inconvenience!

**Comment by gscogna** [comment]
> Sì, anche la mia integrazione è in calo da due mesi. :(. @gscognanon vuoi fare una richiesta push e inviare le tue modifiche al repository ufficiale?

I would also like to address the issue which they have deliberately made incompatible with older versions of php.
In the end I fixed the incompatibilities between the php versions and some problems with the di:compile the rest of the code is the same.
Perhaps the best choice would be to rely on companies like amasty otherwise you can try to use my code, I tested it with no exceptions and it works.
@PhiIipp @Fidelity88

**Comment by VishalAgarwal** [comment]
> Hi @Fidelity88, support for Magento v2.4.6 is coming up in a few weeks, please stay tuned for updates! Apologize for any inconvenience!

Request to please have the same updated on priority as our migration is stopped due to the same.

**Comment by zlik** [comment]
Hi @Fidelity88, we've added 2.4.6 support in https://github.com/magento/meta-for-magento2/releases/tag/v1.1.0. I'm going to close this issue. If you encounter any other issues, please feel free to open a new issue on Github and we'll look into it!
