### ISSUE TITLE
Magento 2.4.6 without Magento_Inventory plugins

### ISSUE THREAD

**Issue by kestraly** [magento/meta-for-magento2#10]
### Description (*)

Ability to add this extension without having the Magento Inventory plugins enabled

### Expected behavior (*)

Ability to save a product without checking vendor/meta/module-catalog/Model/Product/Feed/Builder/MultiSourceInventory.php

### Benefits

Allows clients who have different Inventory management systems to use, such as Boost My Shop ERP

**Comment by pradeepkanaka** [comment]
@kestraly Could you please upgrade the Meta version and validate? This has been fixed already.
https://github.com/magento/meta-for-magento2/commit/b1000797c59af958b1069a6192013fe4f5db5b05#diff-f61774e1e76acf0567dc41801d2a9c6f601e0546c6cd5fe436c56e7b352d952eR26
