### ISSUE TITLE
add to cart conversion dont work correctly

### ISSUE THREAD

**Issue by redati** [magento/meta-for-magento2#11]
### Preconditions (*)

1. add product to cart

### Steps to reproduce (*)

1. configures the store to redirect to the cart after adding the product to the cart.

### Expected result (*)

send add to cart conversion to meta

### Actual result (*)

event is not sent

### config
magento 2.4.6-p1 php8.1, latest module meta

**Comment by Bashev** [comment]
@magento I am working on this

**Comment by davirs** [comment]
@Bashev Could you give some feedback on this?
I'm testing the module here in version 1.3.0 and the problem is the same.
This event is very important! How to solve?

**Comment by priyambad** [comment]
@magento run all tests
