### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by CalzaFino** [magento/meta-for-magento2#12]
It will be great to have at least a brief User Guide for not very-experienced users.

A couple of examples to clarify on the User Guide
---Is there a way ta manage the attributes mapping?
the "default mapping" I am getting so far is not correct. I manage multiple brands and on Meta the "Brand" filed is filled with my company name.

-- I am getting on Meta duplicate items coming from two different data feeds. One feed is called "Facebook For Magento" and uses de Magento product ID to sync to Meta. The other is from a feed called "Magento Autogenerated Feed" using the Magento SKU to sync to Meta
Which none is the correct feed for this application?

**Comment by ajello-meta** [comment]
Hi @CalzaFino, you can find the user guide here https://www.facebook.com/business/help/532749253576163 for **^1.3.0**. We officially launched the extension with [v1.3.0](https://commercemarketplace.adobe.com/meta-meta-for-magento2.html) (currently v1.3.1) on March 26, 2024. 

Please **upgrade to the latest version**, as it is a significant improvement over the previous version, with many new features and a much more stable build. Many issues that existed in previous version have also been resolve!

**Comment by CalzaFino** [comment]
I just started using this module again and after more than a year, the attributes mapping is still not working. Do you have any idea if this will be fixed shortly?

**Comment by zlik** [comment]
@CalzaFino, for visibility, can you please create a new issue with some description around attributes mapping still not working for you? Thanks!
