### ISSUE TITLE
SUPPORT MULTI-SELECT ATTRIBUTES

### ISSUE THREAD

**Issue by kestraly** [magento/meta-for-magento2#16]
### Preconditions (*)

1. Magento 2.4.6
2. PHP 8.1

### Steps to reproduce (*)

1. Create attribute set it as multiselect. 
2. Select two options on the attribute for the product
3. Save product
4. Go to Meta > Configuration and select custom attribute mapping

### Expected result (*)

1. Catalog correctly syncs

### Actual result (*)

1. Failure to sync
2. Cannot convert array to string vendor/meta/module-catalog/Model/Product/Feed/Builder.php - Line 295

Possible solution

`if (is_array($attrValue))  $attrValue = implode(',', $attrValue);`

**Comment by kestraly** [comment]
Alternative solution 

/app/code/Meta/Catalog/Model/Product/Feed/Builder/AdditionalAttributes.php

```
public function getCorrectText(Product $product, string $attribute)
    {
        if ($product->getData($attribute)) {
            $text = $product->getAttributeText($attribute);
            if (!$text) {
                $text = $product->getData($attribute);   
            }
            if (is_array($text))  $text = implode(',', $text);
            return $text;
        }
        return false;
    }
```

**Comment by kestraly** [comment]
Pull request added
https://github.com/magento/meta-for-magento2/pull/45

**Comment by veppywaqar** [comment]
Hello ,

i have mapped brand attribute with my custom attribute of type select and when i am trying to update i can see option ID(int) instead of option label

is there any solution i am using latest Meta extension i.e i.3.2

**Comment by zlik** [comment]
Fixed in https://github.com/magento/meta-for-magento2/commit/88f6e45d86aff9f1413630de5a0848b2d4d13b73. Closing but please feel free to flag if this is still an issue. Thanks!
