### ISSUE TITLE
 Undefined array key "id" in  Undefined array key "id" in vendor/meta/module-catalog/Block/Adminhtml/Diagnostics.php on line 148

### ISSUE THREAD

**Issue by kestraly** [magento/meta-for-magento2#18]
### Preconditions (*)

1. Magento 2.4.6-p1
2. PHP 8.1

### Steps to reproduce (*)

1. Visit Meta / Diagnostics
2. Check system.log

### Expected result (*)

1. Page without errors recorded in system.log

### Actual result (*)

1.  var/log/system.log records the following error Undefined array key "id" in vendor/meta/module-catalog/Block/Adminhtml/Diagnostics.php on line 148

**Comment by zlik** [comment]
catalog diagnostics are moving into Meta iframe
