### ISSUE TITLE
Meta icon in menu isn't grayed out

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/meta-for-magento2#28]
In the latest Meta extension v 1.2.0, the only one non-gray icon is Meta, which very different from other icons
<img width="86" alt="image" src="https://github.com/magento/meta-for-magento2/assets/1873745/577e80fb-a5b5-4da9-a624-a08d086f433e">

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by Bashev** [comment]
We have no daily job with this menu, for me this need to be in Marketing section.

**Comment by zlik** [comment]
@ihor-sviziev, in the new upcoming version we've redesigned the icon to be grayed out and say "Facebook & Instagram" instead of Meta.

@Bashev, thanks for your suggestion, will discuss it with the team internally!

**Comment by zlik** [comment]
The menu item has been redesigned, however we're keeping it in the main menu for now:
<img width="110" alt="Screenshot 2023-11-06 at 3 54 40 PM" src="https://github.com/magento/meta-for-magento2/assets/472255/c79eb738-86d3-479e-985c-c1719d348d28">

**Comment by barbanet** [comment]
Is it possible to review the @Bashev suggestion for the menu?
According to https://developer.adobe.com/commerce/php/best-practices/admin/placement-and-design/#feature-extensions, there should not be a new option at that level in the menu for any module. Either it could be included under Marketing or it should be under Extensions. Right?
