### ISSUE TITLE
Grouped products are synced as simple products

### ISSUE THREAD

**Issue by Bashev** [magento/meta-for-magento2#30]
Grouped products are synced as simple products and if their child products are invisible, they are not linked properly to Catalog.

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by scottnerd** [comment]
@Bashev grouped products are not currently supported by Meta, but may be in the future. Right now we are syncing them with the hope that we will support them soon. The grouped products will be hidden for buying purposes, but are still visible for Ads
