### ISSUE TITLE
No ability to NOT enable catalog integration by default

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/meta-for-magento2#34]
When installing extension and configuring sync, the catalog sync is enabled by default, and even when you don't need it - it starts automatically pushing products to Meta.

It looks like it's caused by https://github.com/magento/meta-for-magento2/blob/c100f2d577c1f3e7245ceccf8334fa4fe5830bff/app/code/Meta/BusinessExtension/Controller/Adminhtml/Ajax/PersistConfiguration.php#L158-L169
and  https://github.com/magento/meta-for-magento2/blob/a58e1d717148ddb2c0f9735c9af8291b737b3e39/app/code/Meta/Catalog/etc/events.xml#L9-L11

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ihor-sviziev** [comment]
Fixed by disabling the Meta_Catalog extension in the config.php file, but it's currently impossible to disable it through admin or at least through `php bin/magento module:disable Meta_Catalog` due to existing dependence from Meta_Sales exntesion.
So far, module is diabled and order sync still works fine

**Comment by zlik** [comment]
@singhramanpreett @cristiannancumeta

**Comment by zlik** [comment]
@ihor-sviziev, I believe in the latest version, we always want for products to be synced to Meta because it improves catalog quality and drives ads performance for the seller. If there's an existing feed coming from other sources than our extension, that shouldn't be a problem – we should be able to correctly resolve any product duplicates.

**Comment by ihor-sviziev** [comment]
@zlik, we just don't want to fight with all the integration all at once, so we would like to start with something simple. And a simple thing is XML feed, which we can generate as a static file and update regularly. This definitely won't generate any not expected load on production, won't cause any exceptions etc.
So from our perspective not having an ability to disable a catalog sync isn't a good thing.

**Comment by zlik** [comment]
> @zlik, we don't want to fight with all the integration all at once (potential issues with different prices, different discounts, conflicts with already installed extensions, solving how to manage product descriptions for different languages, etc), so we would like to start with something simple. A simple thing is an XML feed, which we can generate as a static file and update regularly. This definitely won't generate any unexpected load on production, won't cause any exceptions, etc. So, not having the ability to disable a catalog sync isn't a good thing.

I see your point @ihor-sviziev, makes a lot of sense to me! I'm checking with the team if there's a better way to handle this. We could potentially ask during onboarding whether the seller wants to enable catalog sync or not. Please stay tuned, we should get back to you on this shortly!

**Comment by sol-loup** [comment]
@ihor-sviziev, this as well as your other issue should be resolvable through the configs we exposed
