### ISSUE TITLE
Function name mismatch: isOrdersSyncEnabled vs. isOrderSyncEnabled

### ISSUE THREAD

**Issue by simonrl** [magento/meta-for-magento2#39]
### Preconditions (*)

1. Meta Version 1.2.1
2. Magento Version 2.4.6-p3

### Steps to reproduce (*)

1. Create an order
2. Create a shipment for the order
3. Create a tracking label for the shipment

### Expected result (*)

1. Tracking label created

### Actual result (*)

1. Spinner in backend
2. exception.log: "Call to undefined function `Meta\BusinessExtension\Model\System\Config::isOrdersSyncEnabled()` 

Reason: 
The function is named `isOrderSyncEnabled()`, but is called as `isOrdersSyncEnabled()` in the code

**Comment by zlik** [comment]
Released in [v1.2.1](https://github.com/magento/meta-for-magento2/releases/tag/v1.2.1), closing the issue
