### ISSUE TITLE
faced issues during composer require 

### ISSUE THREAD

**Issue by harishkhant** [magento/meta-for-magento2#4]
We faced issues during install-module.

![image](https://github.com/magento/meta-for-magento2/assets/64633051/62400a38-993e-41c1-863a-0989398637c6)

**Comment by zlik** [comment]
Hi @harishkhant, sorry for your issue. The extension currently does not have the support for Magento v2.4.6, but it's coming up in the next release coming up in a week or two! Please stay tuned for updates.

**Comment by harishkhant** [comment]
any realse date for this new version?

**Comment by zlik** [comment]
This issue was fixed in https://github.com/magento/meta-for-magento2/releases/tag/v1.1.0
