### ISSUE TITLE
State isn't selected in Billing and Shipping addresses

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/meta-for-magento2#40]
We do have state on the Meta side:
![Capture 2023-10-16 at 16 04 13](https://github.com/magento/meta-for-magento2/assets/1873745/a8aac1b0-e8de-44e8-803f-94abe1dfc44b)
While in Magento, this field isn't selected:
<img width="1084" alt="image" src="https://github.com/magento/meta-for-magento2/assets/1873745/03ca740f-68df-4569-aea8-211b4cc7841c">

For instance, this information is mandatory for our integrations with Magento.

### Preconditions (*)

1. Magento v2.4.5-p5
2. Meta for Magento v1.2.0

### Steps to reproduce (*)

1. Configure Meta extension to be integrated with some Page/Commerce Account/Catalog, so that you'll have a Facebook Test Store
2. Wait till the catalog becomes available in the commerce account
3. Go to the Facebook Test store and place some test order
4. Wait till the order will be synced from Facebook to Magento
5. See the billing & shipping information in Magento 

### Expected result (*)

1. You should have a state selected in the Billing and in Shipping Address section

### Actual result (*)

1. The state isn's selected  <img width="1084" alt="image" src="https://github.com/magento/meta-for-magento2/assets/1873745/03ca740f-68df-4569-aea8-211b4cc7841c">

**Comment by zlik** [comment]
@ihor-sviziev, this has been fixed in https://github.com/magento/meta-for-magento2/releases/tag/v1.2.3. Closing the issue.
