### ISSUE TITLE
Error when setting up the extension in the admin panel

### ISSUE THREAD

**Issue by lemaryn** [magento/meta-for-magento2#42]
### Preconditions (*)

1. Magento 2.4.5-p1
2. Meta for Magento v1.2.1

### Steps to reproduce (*)

1. Create a store following the screenshot 
![image](https://github.com/magento/meta-for-magento2/assets/770313/532412a2-5890-4541-88ba-f937da56c29e)
2. Set a debugging breakpoint on this line
https://github.com/magento/meta-for-magento2/blob/v1.2.1/app/code/Meta/BusinessExtension/Block/Adminhtml/Setup.php#L136
3. Go to Setup 
![image](https://github.com/magento/meta-for-magento2/assets/770313/a3d32a15-9746-4277-8aa4-c70e40a156e1)
4. The store key does not match 0
![image](https://github.com/magento/meta-for-magento2/assets/770313/2191dcf0-aa0d-47ac-a075-d72f67ced623)

 

### Expected result (*)

1. Correct page for setup
![image](https://github.com/magento/meta-for-magento2/assets/770313/d8555ef1-5aa4-4429-820e-39d81027ecfd)

### Actual result (*)

1. I see a blank page 
![image](https://github.com/magento/meta-for-magento2/assets/770313/9a0915e8-27f6-4262-b2f4-0814549550d1)
In the log, I see this error 

```shell
[2023-10-20T17:01:24.075689+00:00] report.CRITICAL: Exception: Warning: Undefined array key 0 in /project-magento/vendor/meta/module-business-extension/Block/Adminhtml/Setup.php on line 135 in /project-magento/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /project-magento/vendor/meta/module-business-extension/Block/Adminhtml/Setup.php(135): Magento\Framework\App\ErrorHandler->handler(2, 'Undefined array...', '/project-magento/vendor...', 135)
#1 /project-magento/vendor/meta/module-business-extension/view/adminhtml/templates/store_picker.phtml(13): Meta\BusinessExtension\Block\Adminhtml\Setup->getSelectedStoreId()
``` 

### I suggest 2 options:
  
1. Replace this line https://github.com/magento/meta-for-magento2/blob/v1.2.1/app/code/Meta/BusinessExtension/Block/Adminhtml/Setup.php#L136

from
```php
$firstStore = array_slice($stores, 0, 1)[0];
```  
to
```php
$firstStore = array_shift($stores);
``` 
3. Replace this part of code https://github.com/magento/meta-for-magento2/blob/v1.2.1/app/code/Meta/BusinessExtension/Block/Adminhtml/Setup.php#L127-L135

from
```php
        // Missing or invalid query param, look for a default.
        foreach ($stores as $store) {
            if ($store->isDefault() && $store->getWebsiteId() === $this->getFirstWebsiteId()) {
                return $store['store_id'];
            }
        }

        // No default found, return the first store.
        $firstStore = array_slice($stores, 0, 1)[0];
``` 
to
```php
        $i=0;
        // Missing or invalid query param, look for a default.
        foreach ($stores as $store) {
            if ($store->isDefault() && $store->getWebsiteId() === $this->getFirstWebsiteId()) {
                return $store['store_id'];
            }
            if ($i === 0) {
                // No default found, return the first store.
                $firstStore = $store;
            }
            $i++;
        }
```

**Comment by zlik** [comment]
Thank you for flagging, @lemaryn! Fixed in https://github.com/magento/meta-for-magento2/releases/tag/v1.2.3, closing this issue.
