### ISSUE TITLE
Meta Product Link is mapped to Admin URL by default, not front-end URL.

### ISSUE THREAD

**Issue by william-gooch** [magento/meta-for-magento2#48]
### Summary (*)

When attempting to upload products into a Meta product feed, the default mapping for the Link field corresponds to the admin URL for that product, I imagine the one given by the `getProductUrl` function used here:
https://github.com/magento/meta-for-magento2/blob/e2a98a376ad5b0f73e350a779b154b7299f391de/app/code/Meta/Catalog/Model/Product/Feed/Builder.php#L250-L253

Surely it would make more sense for the default to be mapped to the frontend URL? While it's possible to use a post-process step to just find-and-replace on the URL it probably shouldn't be necessary.

**Comment by vncnt-mb** [comment]
Same problem here (tested 1.2.1 to 1.2.5 & Magento 2.4.6 - 2.4.6-p3)
On my side, only appears when child product (of parent configurable product) is not visible individually.

**Comment by Bashev** [comment]
I think i fix it in my PR https://github.com/magento/meta-for-magento2/pull/22

**Comment by william-gooch** [comment]
Does this PR fix that issue? To me it looks like it only affects product images, not the product link itself.

**Comment by vncnt-mb** [comment]
Do you have any updates on this?
We can't use dynamic ads on Facebook & Instagram at the moment since the problem occurs

All our products are refused because their links are invalid!

**Comment by ptrdelgado2207** [comment]
is there any solution to this problem?

**Comment by zlik** [comment]
Fixed in [1.3.5](https://github.com/magento/meta-for-magento2/releases/tag/v1.3.5), closing the issue.
