### ISSUE TITLE
Issue with Initial Setup - Connection Pending

### ISSUE THREAD

**Issue by jorgepires** [magento/meta-for-magento2#49]
### Preconditions (*)

1. PHP 8.1
2. Magento 2.4.5-p1
3. Plugin version 1.2.5

### Steps to reproduce (*)

1. Configure the plugin with the Meta connector
2.

### Expected result (*)

1.  Setup completes
2.

### Actual result (*)

1.  The plugin remains in status, connection pending
2.
![image](https://github.com/magento/meta-for-magento2/assets/3522296/1a5f1820-984c-4276-9cce-ffc7fb30aa65)

**Comment by rendyep** [comment]
is there any update on this issue? I'm getting the same issue on Magento Cloud environment.
PHP version: 8.1.28
Magento version: 2.4.5-p9
Module version: 1.3.1

**Comment by jczhuoMeta** [comment]
Hello, looks like you are using the legacy interface and we are not supporting it anymore.

To ensure proper experience, please
1. Update your extension to the latest version
2. Ensure
Activate Integration set to true
--


<br class="Apple-interchange-newline">
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/3715a745-8509-4b58-88d0-cefdd00f3f27">
