### ISSUE TITLE
AAMSettingsCron Class does not exists in Meta\BusinessExtension\Cron

### ISSUE THREAD

**Issue by WRCdev** [magento/meta-for-magento2#5]
Probably the instance path in [Meta/Conversion/etc/crontab.xml](https://github.com/magento/meta-for-magento2/blob/fb6053415cfd25b638b620ed04cf4b422be6b001/app/code/Meta/Conversion/etc/crontab.xml#L4) line 4 is incorrect, must be `Meta\Conversion\Cron\AAMSettingsCron` instead `Meta\BusinessExtension\Cron\AAMSettingsCron`

### Preconditions (*)

1. Magento 2.4.5-p3
2. [meta/meta-for-magento2](https://marketplace.magento.com/meta-meta-for-magento2.html) 1.0.1

### Steps to reproduce (*)

1. Execute `php bin/magento cron:run`

### Expected result (*)

1. Cron running succesfully

### Actual result (*)

1. Class “Meta\BusinessExtension\Cron\AAMSettingsCron” does not exist

**Comment by zlik** [comment]
Thank you for reporting the issue, @WRCdev! It will be addressed in the upcoming release.
