### ISSUE TITLE
Push Products to Meta is not generating complete CSV file for 100K Products

### ISSUE THREAD

**Issue by hodtechnologies** [magento/meta-for-magento2#50]
### Preconditions (*)

1.Magento ver. 2.4.6
2.Meta Module Version: 1.2.4

### Steps to reproduce (*)

1. Go to Store -> Configuration -> Facebook and Instagram Extension Setting 
2. Click Push Products to Meta.
3. Its not generating full CSV file under /var/export
4. Struck in between if we have more than 100K Products.

### Expected result (*)

1. This Meta file generate should be a batch process and execute from bin command. not from admin

### Actual result (*)

1. Half file generated and gz.lock file there to prevent from pushing.

**Comment by zlik** [comment]
Please note that the push button was designed to quickly validate that the product feed upload works during development and testing. For a catalog with 100k+ products it will likely time out. However, the daily product feed cron job, designed to be used in production, should work just fine, even for a very large catalog. We'll add a warnings that this feature may not be suitable for extremely large catalogs and will consider making the request async in the future so it won't time out.
