### ISSUE TITLE
_processNestedGroups() must be an instance of Meta\Catalog\Plugin\Backend\Config\mixed, array given

### ISSUE THREAD

**Issue by kestraly** [magento/meta-for-magento2#52]
### Preconditions (*)

1. Install extension and do not configure immediately

### Steps to reproduce (*)

1. Save any configuration in the admin

### Expected result (*)

1. Configuration Saves

### Actual result (*)

1.  Argument 1 passed to Meta\Catalog\Plugin\Backend\Config\SaveController::_processNestedGroups() must be an instance of Meta\Catalog\Plugin\Backend\Config\mixed, array given, called in /vendor/meta/module-catalog/Plugin/Backend/Config/SaveController.php on line 274

**Comment by bulbulmofosys** [comment]
Hello,
any update on this?

**Comment by francescodoffizi** [comment]
Same here, magento 2.4.3-p1 unable to save any Catalog option

**Comment by kestraly** [comment]
I ended up having to wrap if(!is_array($group)) {} at line 274 for each group to get it to save again as a temp solution

**Comment by sol-loup** [comment]
Hey all, the offending  nested groups should have been removed as of 1.3.1. Can you confirm you're still seeing this issue?

**Comment by christianago** [comment]
Same here for Magento 2.4.4

**Comment by kestraly** [comment]
@christianago - Are you on PHP7.4 ? I think it's no longer compatible if that's the case

**Comment by christianago** [comment]
> @christianago - Are you on PHP7.4 ? I think it's no longer compatible if that's the case



> @christianago - Are you on PHP7.4 ? I think it's no longer compatible if that's the case

Yes I am on PHP 7.4. Readme states the min supported version is 7.4. This isn't true in the last version?

**Comment by kestraly** [comment]
@christianago - Just had this issue with Amazon pay. They introduced type MIXED and it basically broke 7.4 compatibility. The fix I put in gets around this, but it's still a pain.

**Comment by zlik** [comment]
This has been addressed in [v1.3.2](https://github.com/magento/meta-for-magento2/releases/tag/v1.3.2): https://github.com/magento/meta-for-magento2/commit/eb84e937171b0ef3064962e875d7942e8464c34c. Closing this issue.
