### ISSUE TITLE
Query error signing into backoffice

### ISSUE THREAD

**Issue by angelo983** [magento/meta-for-magento2#63]
### Preconditions (*)

1. Login into backoffice

### Steps to reproduce (*)

1. Seeing the exception in every page of the backoffice

### Expected result (*)

1. The plugin should be tested with table prefix!

### Actual result (*)

1. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'meta_issue_notifications' doesn't exist, query was: SELECT `meta_issue_notifications`.* FROM `meta_issue_notifications` WHERE (notification_id = 'version_notification')
Exception in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:603

**Comment by sol-loup** [comment]
this is correct

**Comment by zlik** [comment]
This is fixed, closing the task. Thank you, all!
