### ISSUE TITLE
Call to undefined method Vendor/meta/module-sales/Helper/OrderHelper.php:90

### ISSUE THREAD

**Issue by davirs** [magento/meta-for-magento2#64]
### Preconditions (*)

magento 2.4.6-p3
php 8.2
meta 1.3.0

### Steps to reproduce (*)

Install the meta 1.3.0 extension.
I haven't configured the extension yet, it's just installed.

### Expected result (*)

Work with default Magento without breaking anything or throwing exceptions

### Actual result (*)

I can't access any orders in the Magento order panel. An exception occurs:
`#43 {main} {"exception":"[object] (Error(code: 0): Call to undefined method Magento\\Sales\\Api\\Data\\OrderExtension::getFacebookOrderId() at /cache/vendor/meta/module-sales/Helper/OrderHelper.php:90)"} []`

![image](https://github.com/magento/meta-for-magento2/assets/4355062/f554f04f-63c0-4a5a-83e0-d1a88ecb4375)

**Comment by sol-loup** [comment]
Hey Davirs -- https://github.com/magento/meta-for-magento2/blob/755ff588a236e36c3c6818ed9cb2855409229e1b/app/code/Meta/Sales/etc/extension_attributes.xml#L4 defines this field as part of our extension attributes, and should work for sellers as long as the correct 

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
php bin/magento cache:flush

functions were called. Can you confirm you performed correct codegen post install

**Comment by sol-loup** [comment]
No problem -- do you mind closing this issue?
