### ISSUE TITLE
Add to cart page view not record

### ISSUE THREAD

**Issue by vanshaldotcom** [magento/meta-for-magento2#66]
Add to card 
Add to wishlist 
Success page
Login page
Register page
Contact us page
Category page
Search page
My account page

Event not trigger on these page for these page view...

Just install on Magento 2.4.6 with latest Facebook bussines module..
Website: carmudify.com

**Comment by vanshaldotcom** [comment]
Please look into the issue.

**Comment by pradeepkanaka** [comment]
@vanshaldotcom can you please upgrade the meta extension to the latest version and check if the issue is still present?

**Comment by vanshaldotcom** [comment]
Now, it's working, thanks for the support.


I have installed this extension on carmudify.com

**Comment by khanareebtkg** [comment]
Hi @vanshaldotcom was this issue occured due to the ajax cart? Did you get it fixed by disabling the theme and modules? 
If you have this fixed with any customization please let me know 

@zlik @pradeepkanaka @davirs I am facing the similar problem.
