### ISSUE TITLE
Issue with Magento 2.4.2 - Impossible to process constructor argument Parameter #2 [ <required> Magento\Framework\Mview\View\ChangeLogBatchWalkerFactory

### ISSUE THREAD

**Issue by dpotkoc** [magento/meta-for-magento2#67]
### Preconditions (*)

1. Magento CLI 2.4.2 - php 7.4
3. meta-for-magento2 1.3.0 version 

### Steps to reproduce (*)

1. php bin/magento se:up

### Actual result (*)

1. Impossible to process constructor argument Parameter #2 [ <required> Magento\Framework\Mview\View\ChangeLogBatchWalkerFactory $changeLogBatchWalkerFactory ] of Meta\Catalog\Plugin\FacebookCatalogUpdateFullReindexPlugin class
2. Magento 2.4.2 doesn't contain classes **ChangeLogBatchWalker** and **ChangeLogBatchWalkerFactory** which are used in plugin: **\Meta\Catalog\Plugin\FacebookCatalogUpdateFullReindexPlugin**

**Comment by sol-loup** [comment]
Hey @dpotkoc -- as of Nov 22, Magento themselves ended all support for Magento versions older than 2.4.3

https://www.247commerce.co.uk/insights/technical/end-of-support-alert-magento-versions-2-4-0-to-2-4-3-as-of-28th-november-2022-2/

Meta supports 2.4.3 and upwards for our sellers, but cannot guarantee compatibility for lower versions. 

In your case, looking at the history for ChangeLogBatchWalker -- it appears it was renamed from 
Renamed from lib/internal/Magento/Framework/Mview/View/ChangeLogBatchIterator.php -- can you validate whether this file exists in your vendor dir? You may be able to simply rename the import in your local version
