### ISSUE TITLE
RGPD - Cookie European Law

### ISSUE THREAD

**Issue by Amadeco** [magento/meta-for-magento2#75]
Hello there,

A dummy question to the community and developers of this extension, but I do not see anywhere in the code of the different modules the support of the Magento_Cookie module.

I saw you are using JavaScript but Also PHP to set cookies.

Indeed, if you enable the system config "web/cookie/cookie_restriction", Magento must block cookie til the agreement of the visitor. In particular, regardind Meta and the pixel tracking function. Unless you are anonymising the personal datas ?

Your extension is bullet-proof to use ?

Or we must, european users of Magento, needs to develop this feature ?

Thank you for your return

**Comment by zlik** [comment]
@Amadeco, we've addressed your feedback in https://github.com/magento/meta-for-magento2/commit/0fe45613d35632fd7952b52232490bb58d8241b9. Closing the issue.
