### ISSUE TITLE
Magento variable plugin is not defined magento 2

### ISSUE THREAD

**Issue by Shreyaa-dev** [magento/meta-for-magento2#76]
when we click on insert variable button that time magentovariableplugin is not defined got this error so we added adminhtml_system_config_edit.xml and issue is resolved but system configuration layout has been changed why ?    
![image_2024_07_18T10_07_52_873Z](https://github.com/user-attachments/assets/a2ccd5bb-fac8-4791-8f6f-1e3067874112)

**Comment by hardikrocktech** [comment]
please refer https://magento.stackexchange.com/a/374486/114630
