### ISSUE TITLE
No extension attributes after reinstall

### ISSUE THREAD

**Issue by likearocket** [magento/meta-for-magento2#79]
### Preconditions (*)

1. Magento 2.4.7-p1
2. Meta 1.3.2
3. PHP 8.3

### Steps to reproduce (*)

1. Uninstall module
2. Delete related attributes
3. Reinstall module

### Expected result (*)

1. Related attributes (Google Product Category/Send to Facebook etc) are recreated and added to all existing attributes set

### Actual result (*)

1. Attributes are not created. Backstory, I uninstalled the module as it wasn't compatible with the latest Magento version. I had to delete the attributes via MySQL as I could not get a backend product page to open, and now after installing the latest version, the related attributes have not been recreated.

**Comment by vishakhaatrightpoint** [comment]
@zlik , can you please confirm, all below attributes from **meta/module-catalog** should be
> removed on module uninstall
> should be installed/created back when module installed again

The attributes created through **meta/module-catalog**  are

1. sync_to_facebook_catalog
2. google_product_category
3. send_to_facebook
4. meta_product_set_id
