### ISSUE TITLE
Error On Module Sales

### ISSUE THREAD

**Issue by CalzaFino** [magento/meta-for-magento2#8]
### Preconditions (*)
 PHP 8.1
Magento 2.4.6-p1
meta-for-magento2 1.0.1
   ** The module documentation shows the latest release as "1.0.1" but on my composer.json file it is listed in the "require" section as "meta/meta-for-magento2": "^1.1"

### Steps to reproduce (*)
Open any order on Magento Admin Orders Grid

### Expected result (*)
Order details are visible

### Actual result (*)
Blank page with error:
"An error has happened during application run. See exception log for details."

Error on the Exception log:

main.CRITICAL: Error: Cannot instantiate interface Meta\Sales\Api\Data\FacebookOrderInterface in /cache/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /cache/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Meta\\Sales\\Api\\...', Array)
#1 /cache/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Meta\\Sales\\Api\\...', Array)
#2 /cache/generated/code/Meta/Sales/Api/Data/FacebookOrderInterfaceFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Meta\\Sales\\Api...', Array)
#3 /cache/vendor/meta/module-sales/Plugin/OrderGet.php(63): Meta\Sales\Api\Data\FacebookOrderInterfaceFactory->create()
#4 /cache/vendor/magento/framework/Interception/Interceptor.php(146): Meta\Sales\Plugin\OrderGet->afterGet(Object(Magento\Sales\Model\OrderRepository\Interceptor), Object(Magento\Sales\Model\Order\Interceptor), '11563')
#5 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('11563')
#6 /cache/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(23): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins('get', Array, Array)
#7 /cache/vendor/magento/module-payment-services-paypal/Plugin/OrderViewEnvironmentMessage.php(52): Magento\Sales\Model\OrderRepository\Interceptor->get('11563')
#8 /cache/vendor/magento/framework/Interception/Interceptor.php(121): Magento\PaymentServicesPaypal\Plugin\OrderViewEnvironmentMessage->beforeExecute(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor))
#9 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->Magento\Framework\Interception\{closure}()
#10 /cache/generated/code/Magento/Sales/Controller/Adminhtml/Order/View/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callPlugins('execute', Array, Array)
#11 /cache/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->execute()
#12 /cache/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /cache/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /cache/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callParent('dispatch', Array)
#15 /cache/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /cache/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /cache/generated/code/Magento/Sales/Controller/Adminhtml/Order/View/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callPlugins('dispatch', Array, Array)
#19 /cache/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /cache/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Object(Magento\Framework\App\Request\Http))
#21 /cache/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor))
#22 /cache/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /cache/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /cache/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /cache/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /cache/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#28 /cache/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#29 {main} {"exception":"[object] (Error(code: 0): Cannot instantiate interface Meta\\Sales\\Api\\Data\\FacebookOrderInterface at /cache/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121)"} []

**Comment by zlik** [comment]
@CalzaFino, can you please run di compile and try again?

**Comment by CalzaFino** [comment]
It is working after di compile 3 times. Thank you
