### ISSUE TITLE
Fail to install on Magento 2.4.2 with PHP 7.4

### ISSUE THREAD

**Issue by yosefkurniawan** [magento/meta-for-magento2#81]
### Summary (*)

In the README says that it support magento ^2.4.2 and PHP 7.4
But it does not work on my project.  We have tried to install the extention version 1.3.0 and 1.1.0 but no luck.

### Examples (*)

![image](https://github.com/user-attachments/assets/92666085-8d31-4986-89d3-8d980660d565)

![image](https://github.com/user-attachments/assets/9f04c5da-d9d7-423c-9572-f8d7341b43ca)

**Comment by zlik** [comment]
@yosefkurniawan, we will not be supporting 2.4.2 moving forward and will remove it from composer.json soon. We recommend updating to the latest version of Magento. Thanks and apologize for any inconvenience.
