### ISSUE TITLE
Issue of Mapping Dropdown Product Attributes with Meta

### ISSUE THREAD

**Issue by veppywaqar** [magento/meta-for-magento2#82]
### Preconditions (*)

1. Magento 2.4.6-p6 CE
2. Meta Extension Version: 1.3.2

### Steps to reproduce (*)

1. Install And Connect Magento Extension with Meta
2. Go to Catalog Attribute Mapping
3. Map Brand Attribute with a Brand Dropdown Attirbute
4. Run the Catalog Sync

![Screenshot from 2024-08-15 10-22-43](https://github.com/user-attachments/assets/48512e1a-75bf-45bb-adb3-519090c9e7a9)

### Expected result (*)

1. the Option Label (Brand Name) Should Sync to Meta

### Actual result (*)

1. the Option id is syncing to Meta

![Screenshot from 2024-08-15 10-25-55](https://github.com/user-attachments/assets/916bd480-f728-457f-9d56-3bdc90d392b1)

**Comment by CalzaFino** [comment]
I have the same problem.
Magento 2.4.7-p2
Meta Extension Version: 1.3.2
PHP 8.3

**Comment by zlik** [comment]
Fixed in [1.3.5](https://github.com/magento/meta-for-magento2/releases/tag/v1.3.5), closing the issue.
