### ISSUE TITLE
Deduplication: Server vs Client side events

### ISSUE THREAD

**Issue by anilucas79** [magento/meta-for-magento2#85]
### Summary (*)
Does the extension allow for event deduplication? We currently use Client side pixels and upon implementing the extension I noticed that in the Meta UI event test there is deduplication message from the server events even though no event_id parameter has been added to the client side events. Not sure what would be the solution or a way to pass that event_id for client side tracking

**Comment by pradeepkanaka** [comment]
@anilucas79 Could you please share more details of the issue? It would be helpful if you explain it with the screenshots.

**Comment by anilucas79** [comment]
Hello Pradeepkanaka, please disregard. I have since confirmed with meta
that all is working correctly and no issues with the implementation. I was
testing this in incognito and failed to realize that client side isn't
fired by design. Thanks
