### ISSUE TITLE
Error exporting textarea attributes

### ISSUE THREAD

**Issue by fsoich-redstage** [magento/meta-for-magento2#89]
Preconditions (*)

    Magento 2.4.6-p6 Cloud
    Meta Extension 1.3.2
    Catalog Size 100k+

Steps to reproduce (*)

    Connect Magento With meta
    Configure Auto Sync to Meta

Expected result (*)

    Cron Should complete Running
    Products should be uploaded to meta

Actual result (*)

For textarea attributes 
FBE.ERROR: Deprecated Functionality: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /app/vendor/magento/zend-db/library/Zend/Db/Statement.php on line 222 [] []
![image](https://github.com/user-attachments/assets/6d6f3b6e-0273-400a-b7da-1d59986de5df)

**Comment by pradeepkanaka** [comment]
@fsoich-redstage This issue has been fixed on the latest version of Meta. Please upgrade to a newer version of meta and let us know your feedback.
