### ISSUE TITLE
Unable to apply data patch

### ISSUE THREAD

**Issue by Antonio-Bennett** [magento/meta-for-magento2#93]
### Preconditions (*)

1. Extension Version: 1.3.4
2.  Magento Version: 2.4.5

### Steps to reproduce (*)

1.Existing eav attribute set with an `attribute_set_id` of `10` in the `General` `attribute_group_name`
2. `attribute_group_code` is `product-details`

### Expected result (*)

1. Module patches correctly and is installed

### Actual result (*)

1. 
```
Unable to apply data patch Meta\Catalog\Setup\Patch\Data\AddProductAttributes for module Meta_Catalog. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '10-General' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: UPDATE `eav_attribute_group` SET `attribute_set_id` = ?, `attribute_group_name` = ?, `default_id` = ? WHERE (`attribute_group_id`='24')
```

**Comment by zlik** [comment]
Fixed and will be released in `1.3.6` early next year. @Antonio-Bennett please let me know if you need the fix sooner – I can send it to you as a patch.

**Comment by Antonio-Bennett** [comment]
@zlik Hey! Thank you for the quick turnaround. I would absolutely appreciate getting a patch! Let me know the easiest method for you :)

**Comment by zlik** [comment]
@Antonio-Bennett, feel free to save `app/code/Meta/Catalog/Setup/Patch/Data/AddProductAttributes.php` from https://github.com/magento/meta-for-magento2/commit/95aa1ace7f266e7a04aa900a4a219d5e25b1f1dd into your Magento codebase and that should do it. After it gets released as part of the extension, that file can be removed.

**Comment by Antonio-Bennett** [comment]
Thank you! I'll go ahead and do so!
